### PR TITLE
FIX Set full version based on context of query

### PR DESCRIPTION
**Pull request by ScopeyNZ**
This could alternately be solved by checking the context on the client side. A little more convoluted though - and I'll have to let the client side know about the "OriginClass".

### CODE REVIEW

**Comment by unclecheese** [comment]
I'm not sure this will hold up. What if a `Block` owns another `Block`?

**Comment by ScopeyNZ** [comment]
Yeah that's a good point. Client side will have to handle this. I'll think about this a little more

**Comment by unclecheese** [comment]
It's already accounted for by the query: https://github.com/silverstripe/silverstripe-versioned-snapshot-admin/blob/master/src/SnapshotPublishableExtension.php#L27

Is this a PR to improve performance?

**Comment by ScopeyNZ** [comment]
Hmmmn. It wasn't working for me. I'll play around a little more. Might be client code related...

**Pull request closed without merging**
